"""
Voice assistant capability orchestrating finite state machine voice interaction,
speech-to-text, streaming language model inference, text-to-speech synthesis,
barge-in interruption detection, and event broadcasting.
"""

import asyncio
from collections import deque
import logging
from pathlib import Path
import re
import time
import uuid
from typing import Any, Dict, List, Optional

from jarvis.capabilities.base import BaseCapability, PermissionEnum
from jarvis.core.base import HealthStatus, ServiceStatus
from jarvis.core.bus import (
    AudioChunkReady,
    ErrorOccurred,
    MessageBus,
    PlaybackFinished,
    SentenceReady,
    SpeechEnded,
    SpeechStarted,
    TaskCancelled,
    TokenGenerated,
    TranscriptReady,
    WakeDetected,
)
from jarvis.core.fsm import FSMState, VoiceFSM
from jarvis.core.observability import ObservabilityService
from jarvis.providers.audio.vad import VADEngine
from jarvis.providers.base import (
    AudioSessionProtocol,
    LLMProtocol,
    STTProtocol,
    StorageProtocol,
    TTSProtocol,
    WakeWordProtocol,
)
from jarvis.providers.chunker import SentenceChunker
from jarvis.utils.async_utils import BoundedQueue, safe_cancel_task

logger = logging.getLogger("jarvis.capabilities.voice_assistant")

_WAKE_PREFIX_PATTERN = re.compile(
    r"^(?:hey\s+jarvis|jarvis|hello\s+jarvis|hi\s+jarvis|haiya\s+jaaravist|haiya\s+jarvis|haye\s+jarvis|jaara\s+vist)[\s,.:;!?]*",
    re.IGNORECASE,
)


def _strip_wake_word_prefixes(text: str) -> str:
    """Remove leading wake-word salutations from the input transcript."""
    if not text:
        return ""
    clean = text.strip()
    return _WAKE_PREFIX_PATTERN.sub("", clean).lstrip(" ,.:;!?")


def _deduplicate_repeated_phrases(text: str) -> str:
    """Detect and remove consecutive repeated phrases generated by STT hallucination loops."""
    if not text:
        return ""
    words = text.split()
    for n in range(1, 9):
        i = 0
        new_words = []
        while i < len(words):
            pattern = words[i : i + n]
            new_words.extend(pattern)
            i += n
            while i + n <= len(words) and words[i : i + n] == pattern:
                i += n
        if len(new_words) < len(words):
            words = new_words
    return " ".join(words).strip()


class VoiceAssistantCapability(BaseCapability):
    """
    Primary voice processing capability managing speech capture, transcription,
    model streaming, audio synthesis, and real-time user interruption (barge-in).
    """

    name = "voice_assistant"
    required_permissions = [PermissionEnum.AUDIO, PermissionEnum.INTERNET]

    def __init__(
        self,
        fsm: VoiceFSM,
        bus: MessageBus,
        audio_session: AudioSessionProtocol,
        wakeword: WakeWordProtocol,
        stt: STTProtocol,
        llm: LLMProtocol,
        tts: TTSProtocol,
        session_store: StorageProtocol,
        observability: ObservabilityService,
        tool_registry: Optional[Any] = None,
        tool_runner: Optional[Any] = None,
        vad_threshold: float = 0.02,
        silence_duration_ms: int = 1800,
        followup_timeout_s: float = 6.0,
        max_history_turns: int = 10,
    ) -> None:
        self.fsm = fsm
        self.bus = bus
        self.audio_session = audio_session
        self.wakeword = wakeword
        self.stt = stt
        self.llm = llm
        self.tts = tts
        self.session_store = session_store
        self.observability = observability
        self.tool_registry = tool_registry
        self.tool_runner = tool_runner
        self.followup_timeout_s = followup_timeout_s
        self.max_history_turns = max_history_turns

        self.vad = VADEngine(energy_threshold=vad_threshold, silence_duration_ms=silence_duration_ms)
        self.chunker = SentenceChunker()
        self._status = ServiceStatus.UNINITIALIZED

        self._audio_buffer: bytearray = bytearray()
        self._preroll_buffer: deque = deque(maxlen=4)
        self._token_queue: BoundedQueue[str] = BoundedQueue(maxsize=100)
        self._active_task: Optional[asyncio.Task] = None
        self._tts_worker_task: Optional[asyncio.Task] = None
        self._is_cancelled: bool = False
        self._speaking_start_time: float = 0.0
        self._listening_start_time: float = 0.0
        self._consecutive_speech_count: int = 0
        self._speech_energy_accumulator: float = 0.0

    def _seed_audio_buffer_from_preroll(self) -> None:
        """Seed initial listening audio buffer with rolling pre-roll history to prevent cutting off prompt start."""
        self._audio_buffer.clear()
        for chunk in self._preroll_buffer:
            self._audio_buffer.extend(chunk)

    async def initialize(self) -> bool:
        await self.fsm.initialize()
        await self.audio_session.initialize()
        await self.wakeword.initialize()
        await self.stt.initialize()
        await self.llm.initialize()
        await self.tts.initialize()
        await self.session_store.initialize()

        if hasattr(self.audio_session, "subscribe_mic"):
            self.audio_session.subscribe_mic(self._handle_mic_frame)

        self._status = ServiceStatus.RUNNING
        logger.info("VoiceAssistantCapability initialized.")
        return True

    async def _handle_mic_frame(self, pcm_data: bytes) -> None:
        """Process incoming raw audio frames from the microphone stream."""
        if not pcm_data:
            return

        self._preroll_buffer.append(pcm_data)
        current_state = self.fsm.state

        if current_state == FSMState.IDLE:
            t0 = time.perf_counter()
            if await self.wakeword.detect(pcm_data):
                dt_ms = (time.perf_counter() - t0) * 1000.0
                self.observability.record_latency("wake_latency", dt_ms)
                await self.bus.publish(WakeDetected(score=1.0))
                await self.fsm.transition_to(FSMState.WAKE_DETECTED)
                await self.fsm.transition_to(FSMState.LISTENING)
                self._seed_audio_buffer_from_preroll()
                self.vad.reset()
                self._listening_start_time = time.perf_counter()
                await self.bus.publish(SpeechStarted())

        elif current_state == FSMState.LISTENING:
            if not self.vad._in_speech:
                if (
                    self._listening_start_time > 0
                    and (time.perf_counter() - self._listening_start_time > self.followup_timeout_s)
                ):
                    logger.info(
                        f"Listening timeout ({self.followup_timeout_s}s) elapsed without speech. Returning to IDLE."
                    )
                    self._listening_start_time = 0.0
                    self._audio_buffer.clear()
                    self.vad.reset()
                    await self.fsm.transition_to(FSMState.IDLE)
                    return

            self._audio_buffer.extend(pcm_data)
            vad_res = self.vad.process_chunk(pcm_data)

            if vad_res["speech_ended"]:
                await self.bus.publish(SpeechEnded(duration_ms=vad_res["silence_ms"]))
                await self.fsm.transition_to(FSMState.TRANSCRIBING)
                pcm_copy = bytes(self._audio_buffer)
                self._audio_buffer.clear()
                self.vad.reset()
                self._listening_start_time = 0.0
                self._active_task = asyncio.create_task(self._process_utterance(pcm_copy))

        elif current_state == FSMState.SPEAKING:
            if time.perf_counter() - self._speaking_start_time < 0.2:
                self._speech_energy_accumulator = 0.0
                return

            rms = self.vad.calculate_rms(pcm_data)

            # Ignore muted microphones or zero/near-zero digital silence
            if rms < 0.004:
                self._speech_energy_accumulator = 0.0
                return

            speech_threshold = max(0.025, self.vad.energy_threshold * 1.25)

            if rms >= speech_threshold:
                self._speech_energy_accumulator += 1.0
                if self._speech_energy_accumulator >= 2.0:
                    logger.info(
                        f"User barge-in interrupt detected (RMS={rms:.4f}, score={self._speech_energy_accumulator:.1f}). Halting speech output."
                    )
                    self.observability.increment_counter("cancellation_count")
                    await self.cancel()
                    await self.bus.publish(TaskCancelled(reason="Barge-in user speech"))
                    await self.fsm.transition_to(FSMState.LISTENING)
                    self._audio_buffer.clear()
                    self._preroll_buffer.clear()
                    self.vad.reset()
                    self._listening_start_time = time.perf_counter()
                    self._speech_energy_accumulator = 0.0
            else:
                self._speech_energy_accumulator = max(0.0, self._speech_energy_accumulator - 0.5)

    async def _process_utterance(self, pcm_bytes: bytes, session_id: str = "default_session") -> None:
        """Transcribe microphone audio and execute the response generation pipeline."""
        self._is_cancelled = False
        start_time = time.perf_counter()

        try:
            t0 = time.perf_counter()
            transcript = await self.stt.transcribe(pcm_bytes)
            stt_dt = (time.perf_counter() - t0) * 1000.0
            self.observability.record_latency("stt_latency", stt_dt)
            self.observability.log_timeline_event("STT_COMPLETE", duration_ms=stt_dt)

            raw_text = transcript.strip() if transcript else ""
            clean_text = _deduplicate_repeated_phrases(raw_text)
            lower_text = clean_text.lower()
            ignored_hallucinations = {
                "[blank_audio]",
                "(silence)",
                "thank you.",
                "subtitles by",
                "thanks for watching!",
                "i can hear you clearly",
                "please ensure ollama is active",
                "i am processing your request",
                "model response timed out",
                "check if your computer is under high load",
                "then then then",
            }

            if not clean_text or any(h in lower_text for h in ignored_hallucinations):
                logger.info(
                    f"Discarding empty or hallucinated transcript ('{clean_text}'). Returning to IDLE."
                )
                await self.fsm.transition_to(FSMState.IDLE)
                return

            await self.process_text_prompt(clean_text, session_id=session_id, start_time=start_time)

        except asyncio.CancelledError:
            self._is_cancelled = True
            logger.info("Utterance processing task cancelled.")
        except Exception as e:
            logger.error(f"Utterance pipeline exception: {e}", exc_info=True)
            await self.bus.publish(
                ErrorOccurred(component="voice_assistant", message=str(e), exception=e)
            )
            await self.fsm.transition_to(FSMState.ERROR)

    async def _try_execute_tool_intent(self, prompt: str, session_id: str) -> Optional[str]:
        """Check prompt for natural language tool intents (files, search, commands) and execute via ToolRunner."""
        if not self.tool_registry or not self.tool_runner:
            return None

        lower = prompt.lower().strip()
        tool_actions = []

        # 1. Check list directory / files intent
        list_keywords = [
            "list file", "list files", "list directory", "read all the files",
            "read me all the files", "files in", "files on", "files present",
            "what files", "what is present", "what are present", "what's in",
            "what is in", "contents of", "show files", "show directory", "dir", "ls",
            "tell me what files", "tell me what is in", "tell me what's in",
            "tell me what are present", "see files", "get files", "folder contents"
        ]
        folder_mention = ("desktop" in lower or "documents" in lower or "downloads" in lower)
        is_list_intent = any(kw in lower for kw in list_keywords) or (
            folder_mention and any(kw in lower for kw in ["what about", "show", "tell me", "check", "open", "folder"])
        )

        if is_list_intent:
            target_dir = "."
            if "desktop" in lower:
                target_dir = "Desktop"
            elif "downloads" in lower:
                target_dir = "Downloads"
            elif "documents" in lower:
                target_dir = "Documents"
            else:
                # Contextual resolution for follow-up turns ("there", "that folder", "it", etc.)
                if any(ref in lower for ref in ["there", "that folder", "that directory", "it"]) and self.session_store:
                    try:
                        history = await self.session_store.get_history(session_id, limit=6)
                        for turn in reversed(history):
                            c_lower = turn.get("content", "").lower()
                            if "documents" in c_lower:
                                target_dir = "Documents"
                                break
                            elif "desktop" in c_lower:
                                target_dir = "Desktop"
                                break
                            elif "downloads" in c_lower:
                                target_dir = "Downloads"
                                break
                    except Exception:
                        pass
            tool_actions.append(("list_directory", {"path": target_dir}))

        # 2. Check write file intent
        write_keywords = [
            "write in a file", "write to a file", "write in file", "write to file",
            "write a file", "create a file", "create file", "save file", "save to file",
            "make a file", "write text", "write content", "save in a file", "store in a file",
            "create new file"
        ]
        if not tool_actions and any(kw in lower for kw in write_keywords):
            # Extract target filename if mentioned (e.g., test.txt or notes.txt)
            filepath = "notes.txt"
            file_match = re.search(r'[\s/\\\("]((?:[a-zA-Z0-9_\-]+\.)+[a-zA-Z0-9]+)[\s/\\\)"]?', prompt, re.IGNORECASE)
            if file_match:
                filepath = file_match.group(1)
            else:
                name_match = re.search(r'(?:file|named|called)\s+([a-zA-Z0-9_\-\.]+)', prompt, re.IGNORECASE)
                if name_match and name_match.group(1).lower() not in ["for", "me", "a", "file", "and", "in", "to", "with"]:
                    filepath = name_match.group(1)

            if "desktop" in lower and not filepath.lower().startswith("desktop"):
                filepath = f"Desktop/{filepath}"

            # Extract content if mentioned
            content = f"File created by Jarvis AI Voice Assistant based on prompt: '{prompt}'"
            content_match = re.search(r'(?:with content|containing|saying|with text|content:)\s*["\']?([^"\']+)["\']?', prompt, re.IGNORECASE)
            if content_match:
                content = content_match.group(1).strip()

            tool_actions.append(("write_file", {"path": filepath, "content": content}))

        # 3. Check read specific file intent
        read_keywords = [
            "read file", "read a file", "read the file", "read in a file",
            "contents of", "read me contents", "read contents", "open file", "cat file", "show file", "view file"
        ]
        if not tool_actions and any(kw in lower for kw in read_keywords):
            filepath = "notes.txt"
            file_match = re.search(r'[\s/\\\("]((?:[a-zA-Z0-9_\-]+\.)+[a-zA-Z0-9]+)[\s/\\\)"]?', prompt, re.IGNORECASE)
            if file_match:
                filepath = file_match.group(1)
            else:
                name_match = re.search(r'(?:read|contents of|file)\s+(?:file\s+)?([a-zA-Z0-9_\-\.]+)', prompt, re.IGNORECASE)
                if name_match and name_match.group(1).lower() not in ["for", "me", "a", "file", "and", "in", "to", "the"]:
                    filepath = name_match.group(1)

            if "desktop" in lower and not filepath.lower().startswith("desktop"):
                filepath = f"Desktop/{filepath}"
            elif "downloads" in lower and not filepath.lower().startswith("downloads"):
                filepath = f"Downloads/{filepath}"
            elif "documents" in lower and not filepath.lower().startswith("documents"):
                filepath = f"Documents/{filepath}"

            tool_actions.append(("read_file", {"path": filepath}))

        # 4. Check search / information intent
        if not tool_actions and any(kw in lower for kw in ["search", "google", "find me", "find info", "who is", "latest", "lookup", "gemma", "model", "search for", "tell me about", "tell me who"]):
            query = prompt
            for prefix in ["search for", "web search", "google", "find me on", "find me", "find info on", "find", "tell me about", "look up"]:
                if lower.startswith(prefix):
                    query = prompt[len(prefix):].strip()
                    break
            if query:
                search_tool_name = "search_system"
                for name in ["search", "search_system", "search_files"]:
                    if self.tool_registry.get_tool(name):
                        search_tool_name = name
                        break
                tool_actions.append((search_tool_name, {"query": query}))

        # 5. Check shell command intent
        shell_keywords = ["run command", "execute command", "terminal command", "run shell", "exec command"]
        if not tool_actions and any(kw in lower for kw in shell_keywords):
            cmd = prompt
            for kw in shell_keywords:
                if kw in lower:
                    idx = lower.find(kw) + len(kw)
                    cmd = prompt[idx:].strip().lstrip(":\"' ")
                    break
            if cmd:
                tool_actions.append(("run_command", {"command": cmd}))

        if not tool_actions:
            return None

        results_summary = []
        from jarvis.runtime.events import StepStarted, StepCompleted
        from jarvis.tools.schemas import ToolCall
        import uuid

        for tool_name, params in tool_actions:
            pair = self.tool_registry.get_tool(tool_name)
            if not pair:
                continue
            spec, adapter = pair
            call_id = f"call_{uuid.uuid4().hex[:8]}"

            await self.bus.publish(StepStarted(plan_id="voice-plan", step_id=call_id, capability_name="tools", action_name=tool_name))
            call = ToolCall(call_id=call_id, tool_name=tool_name, params=params)
            res = await self.tool_runner.execute_call(call, spec, adapter)
            res_data = getattr(res, "data", getattr(res, "result", None))

            # Fallback: if read_file fails with FILE_NOT_FOUND, search for file across Desktop & workspace
            if not res.success and tool_name == "read_file":
                target_name = Path(params.get("path", "")).name
                if target_name:
                    search_pair = self.tool_registry.get_tool("search_files")
                    if search_pair:
                        s_spec, s_adapter = search_pair
                        s_call = ToolCall(call_id=f"call_{uuid.uuid4().hex[:8]}", tool_name="search_files", params={"pattern": f"*{target_name}*", "path": "Desktop"})
                        s_res = await self.tool_runner.execute_call(s_call, s_spec, s_adapter)
                        s_data = getattr(s_res, "data", getattr(s_res, "result", {}))
                        matches = s_data.get("matches", []) if isinstance(s_data, dict) else []
                        if matches:
                            # Re-run read_file with discovered path
                            found_path = matches[0]
                            r_call = ToolCall(call_id=call_id, tool_name="read_file", params={"path": found_path})
                            res = await self.tool_runner.execute_call(r_call, spec, adapter)
                            res_data = getattr(res, "data", getattr(res, "result", None))

            await self.bus.publish(StepCompleted(plan_id="voice-plan", step_id=call_id, success=res.success, result=res_data if res.success else str(res.error)))

            if res.success:
                if isinstance(res_data, list):
                    items_str = ", ".join([str(x) for x in res_data[:10]])
                    results_summary.append(f"{tool_name} returned: [{items_str}]")
                elif isinstance(res_data, dict):
                    import json
                    results_summary.append(f"{tool_name} returned: {json.dumps(res_data)}")
                else:
                    results_summary.append(f"{tool_name} returned: {res_data}")
            else:
                err_msg = res.error.message if res.error else "Execution failed"
                results_summary.append(f"{tool_name} failed: {err_msg}")

        return "; ".join(results_summary) if results_summary else None

    async def process_text_prompt(
        self,
        transcript: str,
        session_id: str = "default_session",
        start_time: Optional[float] = None,
    ) -> None:
        """Process a text query directly through LLM and TTS pipeline."""
        self._active_task = asyncio.current_task()
        self._is_cancelled = False
        if hasattr(self.audio_session, "reset_stop_flag"):
            self.audio_session.reset_stop_flag()

        if start_time is None:
            start_time = time.perf_counter()

        cleaned_prompt = _strip_wake_word_prefixes(transcript)
        if not cleaned_prompt:
            cleaned_prompt = "Hello! How can I help you today?"

        fallback_occurred = False

        try:
            logger.info(f"Processing prompt: '{cleaned_prompt}' (raw: '{transcript}')")
            await self.bus.publish(TranscriptReady(text=cleaned_prompt))
            await self.session_store.save_turn(session_id, "user", cleaned_prompt)

            await self.fsm.transition_to(FSMState.THINKING)

            # Check if prompt triggers explicit tool execution
            tool_summary = await self._try_execute_tool_intent(cleaned_prompt, session_id)
            if tool_summary:
                llm_prompt = f"The user asked: '{cleaned_prompt}'. I executed the tool(s) and got result: {tool_summary}. Provide a 1-sentence concise response to the user."
            else:
                llm_prompt = cleaned_prompt

            if self.max_history_turns > 0:
                history = await self.session_store.get_history(session_id, limit=self.max_history_turns)
                formatted_history = (
                    [{"role": turn["role"], "content": turn["content"]} for turn in history[:-1]]
                    if len(history) > 1
                    else []
                )
            else:
                formatted_history = []

            t_llm_start = time.perf_counter()
            first_token_received = False
            full_response_text = ""

            self.chunker.reset()
            sentence_queue: asyncio.Queue = asyncio.Queue()
            self._tts_worker_task = asyncio.create_task(self._tts_pipeline_worker(sentence_queue))

            async for token in self.llm.generate_stream(llm_prompt, formatted_history):
                if self._is_cancelled:
                    break

                if not first_token_received:
                    ttft = (time.perf_counter() - t_llm_start) * 1000.0
                    self.observability.record_latency("ttft", ttft)
                    self.observability.log_timeline_event("TTFT", duration_ms=ttft)
                    first_token_received = True

                full_response_text += token
                await self.bus.publish(TokenGenerated(token=token, accumulated_text=full_response_text))

                sentence_chunks = self.chunker.add_token(token)
                for sentence in sentence_chunks:
                    if self._is_cancelled:
                        break
                    await sentence_queue.put(sentence)

            remaining_sentence = self.chunker.flush()
            if remaining_sentence and not self._is_cancelled:
                await sentence_queue.put(remaining_sentence)

            if not full_response_text.strip() and not self._is_cancelled:
                fallback_msg = "I heard you clearly! How can I help you today?"
                full_response_text = fallback_msg
                await sentence_queue.put(fallback_msg)

            # Signal end of sentence stream and await synthesis task completion
            await sentence_queue.put(None)
            if self._tts_worker_task:
                await self._tts_worker_task

            if not self._is_cancelled and hasattr(self.audio_session, "wait_for_playback_complete"):
                await self.audio_session.wait_for_playback_complete()

            await self.bus.publish(PlaybackFinished())

            if (
                getattr(self.llm, "has_error", False)
                or "please ensure ollama is active" in full_response_text.lower()
            ):
                fallback_occurred = True

            if full_response_text and not self._is_cancelled and not fallback_occurred:
                await self.session_store.save_turn(session_id, "assistant", full_response_text)

            total_dt = (time.perf_counter() - start_time) * 1000.0
            self.observability.record_latency("total_response_latency", total_dt)
            self.observability.log_timeline_event("RESPONSE_COMPLETE", duration_ms=total_dt)

        except asyncio.CancelledError:
            self._is_cancelled = True
            logger.info("Text prompt task cancelled.")
        except Exception as e:
            logger.error(f"Text prompt execution error: {e}", exc_info=True)
            await self.bus.publish(
                ErrorOccurred(component="voice_assistant", message=str(e), exception=e)
            )
            await self.fsm.transition_to(FSMState.ERROR)
        finally:
            self._audio_buffer.clear()
            self.vad.reset()
            if not self._is_cancelled and self.fsm.state != FSMState.ERROR:
                if fallback_occurred:
                    logger.info("LLM fallback triggered; returning to IDLE state.")
                    await self.fsm.transition_to(FSMState.IDLE)
                else:
                    logger.info("Turn completed. Transitioning to LISTENING state.")
                    self._listening_start_time = time.perf_counter()
                    await self.fsm.transition_to(FSMState.LISTENING)

    async def _tts_pipeline_worker(self, sentence_queue: asyncio.Queue) -> None:
        """Background worker consuming queued text sentences and streaming synthesis into speaker queue."""
        first_chunk = True

        while not self._is_cancelled:
            try:
                sentence = await sentence_queue.get()
            except asyncio.CancelledError:
                break

            if sentence is None:
                sentence_queue.task_done()
                break

            if self._is_cancelled or getattr(self.audio_session, "_stop_requested", False):
                sentence_queue.task_done()
                continue

            if self.fsm.state != FSMState.SPEAKING:
                self._speaking_start_time = time.perf_counter()
                self._speech_energy_accumulator = 0.0
                await self.fsm.transition_to(FSMState.SPEAKING)

            await self.bus.publish(SentenceReady(sentence=sentence))

            t_tts_start = time.perf_counter()

            try:
                async for audio_chunk in self.tts.synthesize_stream(sentence):
                    if self._is_cancelled or getattr(self.audio_session, "_stop_requested", False):
                        logger.info("Speech synthesis aborted due to cancellation.")
                        break

                    if first_chunk:
                        tts_fa = (time.perf_counter() - t_tts_start) * 1000.0
                        self.observability.record_latency("tts_first_audio", tts_fa)
                        first_chunk = False

                    await self.bus.publish(AudioChunkReady(audio_bytes=audio_chunk.data))
                    await self.audio_session.play_audio_chunk(audio_chunk)
            except Exception as synth_err:
                logger.error(f"Error during streaming sentence synthesis: {synth_err}")
            finally:
                sentence_queue.task_done()

    async def _synthesize_and_speak(self, sentence: str) -> None:
        """Synthesize single sentence text to speech audio chunks and queue for playback."""
        if not sentence or self._is_cancelled or getattr(self.audio_session, "_stop_requested", False):
            return

        sentence_queue: asyncio.Queue = asyncio.Queue()
        self._tts_worker_task = asyncio.create_task(self._tts_pipeline_worker(sentence_queue))
        await sentence_queue.put(sentence)
        await sentence_queue.put(None)
        await self._tts_worker_task

        if not self._is_cancelled and hasattr(self.audio_session, "wait_for_playback_complete"):
            await self.audio_session.wait_for_playback_complete()

        await self.bus.publish(PlaybackFinished())
        self._audio_buffer.clear()
        self.vad.reset()

    async def execute(self, action: str, params: Dict[str, Any], session_id: str) -> Any:
        """Execute capability actions requested by the task executor."""
        if action == "process_voice":
            pcm = params.get("pcm_data", b"")
            if pcm:
                await self._process_utterance(pcm, session_id=session_id)
            else:
                prompt = params.get("prompt", "Hello")
                await self.process_text_prompt(prompt, session_id=session_id)
            return "Voice processed successfully"
        return "Unknown action"

    async def health(self) -> HealthStatus:
        return HealthStatus(
            status=self._status,
            message="VoiceAssistantCapability active",
            details={
                "fsm_state": self.fsm.state.value,
                "audio_buffer_size": len(self._audio_buffer),
            },
        )

    async def shutdown(self) -> None:
        await self.cancel()
        await self.fsm.shutdown()
        await self.audio_session.shutdown()
        await self.stt.shutdown()
        await self.llm.shutdown()
        await self.tts.shutdown()
        await self.session_store.shutdown()
        self._status = ServiceStatus.STOPPED

    async def cancel(self) -> None:
        self._is_cancelled = True
        await self.audio_session.stop_playback()
        await self.tts.cancel()
        await self.llm.cancel()
        if self.wakeword and hasattr(self.wakeword, "reset"):
            self.wakeword.reset()
        await self.bus.publish(TaskCancelled(reason="Barge-in / User Cancellation"))
        current = asyncio.current_task()
        if self._tts_worker_task and self._tts_worker_task != current:
            await safe_cancel_task(self._tts_worker_task)
            self._tts_worker_task = None
        if self._active_task and self._active_task != current:
            await safe_cancel_task(self._active_task)
            self._active_task = None


